import { Message, Task, Subtask, FileNode, DatabaseStatus } from "../src/types.js";
import { AppEnv, D1Database, resolveEnvWithOverrides } from "./env.js";
import * as fs from "fs";
import * as path from "path";

// ── Agent Workspace Isolation ─────────────────────────────────────────────────
// All files generated by the agent are written to agent-workspace/ to prevent
// overwriting root project files (package.json, index.html, vite.config.ts, etc.)
const AGENT_WORKSPACE_DIR = "agent-workspace";

function toAgentPath(filePath: string): string {
  // Strip leading / if present
  const clean = filePath.replace(/^\/+/, "");
  // If already prefixed with agent-workspace/, leave it alone
  if (clean.startsWith(AGENT_WORKSPACE_DIR + "/") || clean === AGENT_WORKSPACE_DIR) {
    return clean;
  }
  return path.join(AGENT_WORKSPACE_DIR, clean);
}

/** Resolve a file path safely within agent-workspace; returns null if path traversal detected */
function resolveAgentPath(rootPath: string, filePath: string): string | null {
  const agentRoot = path.resolve(rootPath, AGENT_WORKSPACE_DIR);
  const resolved  = path.resolve(rootPath, toAgentPath(filePath));
  if (!resolved.startsWith(agentRoot)) return null; // path traversal guard
  return resolved;
}

// ── Local in-memory fallback (when D1 not available) ─────────────────────────
interface LocalDbSchema {
  messages: Message[];
  tasks:    Task[];
  files:    FileNode[];
}

let localDb: LocalDbSchema = { messages: [], tasks: [], files: [] };
let db: D1Database | null = null;
let useLocalMemory = true;

const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    task_id TEXT,
    actions_taken TEXT,
    thought_time_seconds REAL,
    model_name TEXT,
    duration_seconds REAL,
    attachment TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    progress INTEGER NOT NULL,
    active_subtask_index INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS subtasks (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    logs TEXT NOT NULL,
    code TEXT,
    file TEXT,
    started_at TEXT,
    completed_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS files (
    path TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    language TEXT NOT NULL
  )`,
];

export async function initDb(env?: Partial<AppEnv>): Promise<DatabaseStatus> {
  const resolved = resolveEnvWithOverrides(env);

  if (!resolved.DB) {
    console.log("[DB] No D1 binding. Using in-memory persistence.");
    useLocalMemory = true;
    db = null;
    return { d1: "local_fallback", kv: "local_fallback" };
  }

  try {
    db = resolved.DB;
    for (const statement of SCHEMA_STATEMENTS) {
      await db.prepare(statement).run();
    }
    try { await db.prepare("ALTER TABLE messages ADD COLUMN attachment TEXT").run(); } catch (_) {}
    useLocalMemory = false;
    console.log("[DB] Connected to Cloudflare D1.");
    return { d1: "connected", kv: "local_fallback" };
  } catch (err: any) {
    console.error("[DB] D1 init error, falling back to in-memory:", err.message);
    useLocalMemory = true;
    db = null;
    return { d1: "error", kv: "local_fallback" };
  }
}

// ── Messages ──────────────────────────────────────────────────────────────────

export async function getMessages(): Promise<Message[]> {
  if (useLocalMemory || !db) return localDb.messages;
  try {
    const res = await db.prepare("SELECT * FROM messages ORDER BY timestamp ASC").all<any>();
    return (res.results || []).map((row) => ({
      id:                  row.id,
      role:                row.role,
      content:             row.content,
      timestamp:           row.timestamp,
      taskId:              row.task_id || undefined,
      actionsTaken:        row.actions_taken        ? JSON.parse(row.actions_taken)  : undefined,
      thoughtTimeSeconds:  row.thought_time_seconds ?? undefined,
      modelName:           row.model_name            || undefined,
      durationSeconds:     row.duration_seconds      ?? undefined,
      attachment:          row.attachment            ? JSON.parse(row.attachment)     : undefined,
    }));
  } catch (err) {
    console.error("[DB] Failed to query messages:", err);
    return localDb.messages;
  }
}

export async function addMessage(msg: Message): Promise<void> {
  if (useLocalMemory || !db) { localDb.messages.push(msg); return; }
  try {
    await db.prepare(`
      INSERT INTO messages (id, role, content, timestamp, task_id, actions_taken, thought_time_seconds, model_name, duration_seconds, attachment)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(id) DO UPDATE SET content = excluded.content, actions_taken = excluded.actions_taken, attachment = excluded.attachment
    `).bind(
      msg.id, msg.role, msg.content, msg.timestamp,
      msg.taskId              ?? null,
      msg.actionsTaken        ? JSON.stringify(msg.actionsTaken) : null,
      msg.thoughtTimeSeconds  ?? null,
      msg.modelName           ?? null,
      msg.durationSeconds     ?? null,
      msg.attachment          ? JSON.stringify(msg.attachment)   : null,
    ).run();
  } catch (err) {
    console.error("[DB] Failed to insert message:", err);
    localDb.messages.push(msg);
  }
}

export async function clearMessages(): Promise<void> {
  if (useLocalMemory || !db) { localDb.messages = []; return; }
  try { await db.prepare("DELETE FROM messages").run(); } catch (err) { console.error("[DB] Failed to clear messages:", err); }
}

// ── Tasks ─────────────────────────────────────────────────────────────────────

export async function getTasks(): Promise<Task[]> {
  if (useLocalMemory || !db) return localDb.tasks;
  try {
    const taskRows    = await db.prepare("SELECT * FROM tasks ORDER BY created_at ASC").all<any>();
    const subtaskRows = await db.prepare("SELECT * FROM subtasks ORDER BY started_at ASC").all<any>();
    const subtaskMap: Record<string, Subtask[]> = {};
    for (const row of subtaskRows.results || []) {
      if (!subtaskMap[row.task_id]) subtaskMap[row.task_id] = [];
      subtaskMap[row.task_id].push({
        id: row.id, taskId: row.task_id, name: row.name, status: row.status,
        logs: JSON.parse(row.logs || "[]"), code: row.code || undefined,
        file: row.file || undefined, startedAt: row.started_at || undefined, completedAt: row.completed_at || undefined,
      });
    }
    return (taskRows.results || []).map(row => ({
      id: row.id, name: row.name, status: row.status,
      progress: row.progress, activeSubtaskIndex: row.active_subtask_index,
      createdAt: row.created_at, startedAt: row.started_at || undefined, completedAt: row.completed_at || undefined,
      subtasks: subtaskMap[row.id] || [],
    }));
  } catch (err) {
    console.error("[DB] Failed to query tasks:", err);
    return localDb.tasks;
  }
}

export async function saveTask(task: Task): Promise<void> {
  if (useLocalMemory || !db) {
    const idx = localDb.tasks.findIndex(t => t.id === task.id);
    if (idx >= 0) localDb.tasks[idx] = task; else localDb.tasks.push(task);
    return;
  }
  try {
    await db.prepare(`
      INSERT INTO tasks (id, name, status, progress, active_subtask_index, created_at, started_at, completed_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(id) DO UPDATE SET
        name=excluded.name, status=excluded.status, progress=excluded.progress,
        active_subtask_index=excluded.active_subtask_index, started_at=excluded.started_at, completed_at=excluded.completed_at
    `).bind(
      task.id, task.name, task.status, task.progress, task.activeSubtaskIndex,
      task.createdAt, task.startedAt ?? null, task.completedAt ?? null,
    ).run();
    for (const st of task.subtasks) {
      await db.prepare(`
        INSERT INTO subtasks (id, task_id, name, status, logs, code, file, started_at, completed_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id) DO UPDATE SET
          status=excluded.status, logs=excluded.logs, code=excluded.code,
          file=excluded.file, started_at=excluded.started_at, completed_at=excluded.completed_at
      `).bind(
        st.id, st.taskId, st.name, st.status,
        JSON.stringify(st.logs), st.code ?? null, st.file ?? null,
        st.startedAt ?? null, st.completedAt ?? null,
      ).run();
    }
  } catch (err) {
    console.error("[DB] Failed to save task:", err);
  }
}

export async function deleteTasks(): Promise<void> {
  if (useLocalMemory || !db) { localDb.tasks = []; return; }
  try {
    await db.prepare("DELETE FROM subtasks").run();
    await db.prepare("DELETE FROM tasks").run();
  } catch (err) { console.error("[DB] Failed to delete tasks:", err); }
}

// ── Files ─────────────────────────────────────────────────────────────────────

export async function getFiles(): Promise<FileNode[]> {
  if (useLocalMemory || !db) return localDb.files;
  try {
    const res = await db.prepare("SELECT * FROM files").all<any>();
    return (res.results || []).map(row => ({ path: row.path, content: row.content, language: row.language }));
  } catch (err) {
    console.error("[DB] Failed to query files:", err);
    return localDb.files;
  }
}

export async function saveFile(file: FileNode): Promise<void> {
  // 1. DB persistence (stores the logical path the agent uses, without prefix)
  if (useLocalMemory || !db) {
    const idx = localDb.files.findIndex(f => f.path === file.path);
    if (idx >= 0) localDb.files[idx] = file; else localDb.files.push(file);
  } else {
    try {
      const check = await db.prepare("SELECT path FROM files WHERE path = ?").bind(file.path).first();
      if (check) {
        await db.prepare("UPDATE files SET content = ?, language = ? WHERE path = ?").bind(file.content, file.language, file.path).run();
      } else {
        await db.prepare("INSERT INTO files (path, content, language) VALUES (?, ?, ?)").bind(file.path, file.content, file.language).run();
      }
    } catch (err) { console.error("[DB] Failed to save file in D1:", err); }
  }

  // 2. Physical write — ISOLATED to agent-workspace/ directory
  // This prevents agent-generated files from overwriting the host project's
  // own package.json, index.html, vite.config.ts, src/main.tsx, etc.
  try {
    if (typeof process !== "undefined" && process.cwd && fs && fs.writeFileSync) {
      const rootPath = process.cwd();
      const resolved = resolveAgentPath(rootPath, file.path);

      if (!resolved) {
        console.warn(`[AgentWorkspace] Blocked path traversal attempt for: ${file.path}`);
        return;
      }

      const targetDir = path.dirname(resolved);
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }
      fs.writeFileSync(resolved, file.content, "utf8");
      console.log(`[AgentWorkspace] Wrote: ${toAgentPath(file.path)}`);
    }
  } catch (fsErr: any) {
    console.warn(`[AgentWorkspace] Physical write failed for ${file.path}:`, fsErr.message);
  }
}

export async function clearFiles(): Promise<void> {
  if (useLocalMemory || !db) { localDb.files = []; return; }
  try { await db.prepare("DELETE FROM files").run(); } catch (err) { console.error("[DB] Failed to clear files:", err); }
}

/** Read a file from agent-workspace on disk (for preview compilation). */
export function readAgentFile(filePath: string): string | null {
  try {
    if (typeof process !== "undefined" && fs && fs.existsSync) {
      const rootPath = process.cwd();
      const resolved = resolveAgentPath(rootPath, filePath);
      if (resolved && fs.existsSync(resolved)) {
        return fs.readFileSync(resolved, "utf8");
      }
    }
  } catch (_) {}
  return null;
}

/** List all physical files in agent-workspace on disk. */
export function listAgentWorkspaceFiles(): string[] {
  try {
    if (typeof process !== "undefined" && fs && fs.existsSync) {
      const rootPath    = process.cwd();
      const agentRoot   = path.join(rootPath, AGENT_WORKSPACE_DIR);
      if (!fs.existsSync(agentRoot)) return [];
      return walkDir(agentRoot).map(f => path.relative(agentRoot, f));
    }
  } catch (_) {}
  return [];
}

function walkDir(dir: string): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (fs.statSync(full).isDirectory()) {
      results.push(...walkDir(full));
    } else {
      results.push(full);
    }
  }
  return results;
}
